### ISSUE TITLE
Does this support android platform ?

### ISSUE THREAD

**Issue by mangorui** [vizor-games/InfraworldRuntime#15]
Our recent project needs to support android grpc in ue4.  Could you tell me  if this plugin supports the android platform?

**Comment by nikomoravec** [comment]
Hello @mangorui! InfraworldRuntime does not support Android platform at this time. But you can try compile [grpc](https://github.com/grpc/grpc) for android and link grpc android libraries to InfrawoldRuntime plugin. For some grpc building examples for Unreal Engine you can look at [Setup.sh](https://github.com/vizor-games/InfraworldRuntime/blob/master/Setup.sh), [Setup.bat](https://github.com/vizor-games/InfraworldRuntime/blob/master/Setup.bat) and [Setup.command](https://github.com/vizor-games/InfraworldRuntime/blob/master/Setup.command) files.

Also, if you will be succeed with grpc building for Android you will need to add Android platform to [InfraWorldRuntime.Build.cs](https://github.com/vizor-games/InfraworldRuntime/blob/master/Source/InfraworldRuntime/InfraWorldRuntime.Build.cs) file.

**Comment by mangorui** [comment]
Thanks for your kind reply!  👍

**Comment by lsjostro** [comment]
might find some hints here https://blog.experium.online/computer-programming/apis-and-frameworks/cross-compile-grpc-unity/
