### ISSUE TITLE
InfraworldExample/Server missing from sample project

### ISSUE THREAD

**Issue by agearhart** [vizor-games/InfraworldRuntime#5]
After downloading and unzipping the linked example project InfraworldExample/Server folder does not exist.

**Comment by nikomoravec** [comment]
Hi agearhart!
Please try this [demo client](https://drive.google.com/file/d/13EZzP_9033vBC7VzJf9LFrygg42LHaOW/view), and this is [demo server](https://www.dropbox.com/s/7ujh8h6kciuugog/vizor-demo-grpc-server.zip?dl=1)
If you have any troubles - feel free to leave comment.
Best regards,
Nikita Miroshnichenko

**Comment by agearhart** [comment]
Do you have example code for running a GRPC server in Unreal with classes generated by https://github.com/vizor-games/infraworld-protobuild by chance?

**Comment by RChehowski** [comment]
Welcome again, @agearhart!

Unfortunately, not yet :( But if you've wrote one, please append it to our project, it will be very useful. By the way, we're planning a new release with some refactoring and performance improvements. Thanks.

**Comment by nielslanting** [comment]
@nikitamiroshnichenko I tried to setup the current master with the demo client. 
`fatal error C1189: #error:  This file was generated by an older version of protoc which is`

Did I screw up something during installation or is the demo client outdated?

**Comment by lsjostro** [comment]
@nielslanting you need to regenerate from the proto file (which I believe is not included). As the release has a newer version then the example.

**Comment by nielslanting** [comment]
@lsjostro Thanks for the quick reply.  I could not find the proto file anywhere, I tried to recreate it. 
https://gist.github.com/nielslanting/f819f456db57c8cfa5fcc28b0f3dfc86

I am uncertain how I should build the .proto file for this project. Am I supposed to use the `infraworld-protobuild` repository? The `infraworld-cornerstone` doesn't generate the wrappers. I tried to manually build them, `protoc -I ./ --cpp_out=./ vizor_demonstration.proto` `
protoc -I ./ --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe --grpc_out=./ vizor_demonstration.proto`, not getting the right files out of this.

Can you tell me how I should build a proto file to work with this project?

**Comment by lsjostro** [comment]
something like this would work. 
```
# Generate wrappers
~/UnrealEngine/Engine/Plugins/Marketplace/InfraworldRuntime/GrpcPrograms/Linux/protoc \
    -I $(realpath ~)/Projects/mygame/Api/ \
    --plugin=protoc-gen-grpc=$(realpath ~)/Projects/UnrealEngine/Engine/Plugins/Marketplace/InfraworldRuntime/GrpcPrograms/Linux/grpc_cpp_plugin \
    --cpp_out=Source/MyService/Private/Wrappers/coolapi \
    --grpc_out=Source/MyService/Private/Wrappers/coolapi \
    $(realpath ~)/Projects/mygame/Api/*.proto
```

**Comment by nikomoravec** [comment]
@agearhart we created an separate repository for example project. Demo Server located at `DemoServer` directory. Please look https://github.com/vizor-games/InfraworldRuntimeExample

**Comment by agearhart** [comment]
Fantastic, thank you!  I've gone another route entirely, but may tinker with this during free time.

**Comment by RChehowski** [comment]
I'm closing this issue for now. Feel free to open an another one if you have something's still unclear.
